apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvc
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc
