apiVersion: v1
kind: PersistentVolume
metadata:
  labels: 
    storage: slow-storage
  name: pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
  storageClassName: giropops
