apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: pvc
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: giropops
  selector:
    matchLabels:
      storage: slow-storage
