apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-app
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
        resources:
          limits:
            cpu: 0.2
            memory: 128Mi
          requests:
            cpu: 0.15
            memory: 64Mi
