apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: nginx
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  template:
    metadata:
      labels: 
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.25.4
        name: nginx
        resources: 
          limits:
            cpu: 0.3
            memory: 256Mi
          requests:
            cpu: 0.2
            memory: 128Mi
