apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: girus-1
  name: girus-1
spec:
  containers:
  - image: nginx 
    name: girus-1
    volumeMounts:
    - mountPath: /giropops
      name: volume-nginx
    resources:
      limits:
        cpu: "0.2"
        memory: "64Mi"
      requests:
        cpu: "0.15"
        memory: "32Mi"
  - image: redis
    name: girus-2
    resources: 
      limits:
        cpu: "0.25"
        memory: "128Mi"
      requests:
        cpu: "0.2"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: volume-nginx
      emptyDir: 
        sizeLimit: 256Mi
status: {}
